#!/bin/bash

OPTIMAL_TIME=2  # time between optimal spreads in days

# date_diff "date1" "date2"
date_diff() {
	d1=$(date -d "$1" +%s)
	d2=$(date -d "$2" +%s)
	echo $(( d2 - d1 ))
}

last=$(cat /home/$USER/.config/dwm/last-spread.dat)
diff_sec=$(date_diff "$last" "$(date)")
diff_days=$(( $diff_sec / 86400 ))
diff_sec=$(( $diff_sec - ( $diff_days * 86400 ) ))
diff_hours=$(( $diff_sec / 3600 ))
diff_sec=$(( $diff_sec - ( $diff_hours * 3600 ) ))

if [[ $diff_days -ge $OPTIMAL_TIME ]]; then
	echo -e "WARNING! WARNING! WARNING!\nYour dwm configuration has not been spread in:\n\t${diff_days} days\n\t${diff_hours} hours!!\nConsider spreading it now!"
fi

