#!/bin/bash

separator=""

get_volume() {
	state=$(amixer sget Master | grep -oP '\[.*\]' | tr ' ' '\n' | tail -1 | sed 's/\(\[\|\]\)//g')
	volume=$(amixer sget Master | grep -oP '\[.*\]' | tr ' ' '\n' | head -1 | sed 's/\(\[\|\]\)//g')
	echo "audio=[$state $volume]"
}

get_network() {
	is_connected=$(ping -c 1 1.1.1.1 &> /dev/null || echo not)
	if [[ ! $(echo "$is_connected" | wc -c) -gt 2 ]]; then
		ipv6=$(curl -s https://www.whatismyip.com/ | grep -oP '<a id="(ipv6|ipv4)".*</a>' | grep -oP '">.*</a>' | sed -e 's/>/\n/g' -e 's/</\n/g' | head -2 | tail -1)
		ipv4=$(curl -s ifconfig.me)
		[[ $(($(echo -n $ipv6 | wc -c) + 0)) -gt 15 ]] && ipv6="on" || ipv6="off"
		[[ $(($(echo -n $ipv4 | wc -c) + 0)) -gt 5 ]] && ipv4="on" || ipv4="off"
		echo "net=[connected IPv6=$ipv6 IPv4=$ipv4]"
	else
		echo "net=[disconnected]"
	fi
}

status() {
	echo "$(get_network) $separator $(get_volume)"
}

date_info() {
	echo $(date +%d\ %B\ \'%y\ %R)
}

while true; do
	xsetroot -name " $(status) $separator $(date_info) "
	now=$(date +%s)
	to=$((($(($now/60)) + 1) * 60))
	sleep $(($to - $now + 1))
done
