#!/bin/bash

separator="\\uf0da"

get_volume() {
	# state=$(amixer sget Master | grep -oP '\[.*\]' | tr ' ' '\n' | tail -1 | sed 's/\(\[\|\]\)//g')
	# volume=$(amixer sget Master | grep -oP '\[.*\]' | tr ' ' '\n' | head -1 | sed 's/\(\[\|\]\)//g')
	state=$(pactl get-sink-mute 1 | cut -d " " -f 2)
	volume=$(pactl get-sink-volume 1 | cut -d "/" -f 2 | xargs | cut -d " " -f 1)

	if [[ "$state" == "no" ]]; then
		echo "\\uf028 $volume"
	else
		echo "\\uf026 ---%"
	fi
}

get_network() {
	is_connected=$(iwctl station wlan0 show | head -6 | tail -n +6 | tr -s '[:space:]' | rev | cut -d\  -f2 | rev)	
	if [[ "$is_connected" == "connected" ]]; then
		# Check VPN
		vpn="\\uf838"
		vpn_procs=$(($(ps aux | grep openvpn | wc -l) + 0))
		[[ $vpn_procs -gt 1 ]] && vpn="VPN "

		echo "$vpn"  # Connected
	else
		echo "\\uf839"  # Disconnected
	fi
}

status() {
	echo "$(get_network) $separator $(get_volume)"
}

date_info() {
	echo $(date +%d\ %B\ \'%y\ %R)
}

while true; do
	xsetroot -name " $(echo -e $(status) $separator $(date_info)) "
	sleep 5
done

