#!/bin/bash

separator="\\uf0da"

get_volume() {
	state=$(amixer sget Master | grep -oP '\[.*\]' | tr ' ' '\n' | tail -1 | sed 's/\(\[\|\]\)//g')
	volume=$(amixer sget Master | grep -oP '\[.*\]' | tr ' ' '\n' | head -1 | sed 's/\(\[\|\]\)//g')

	if [[ "$state" == "on" ]]; then
		echo "\\uf028 $volume"
	else
		echo "\\uf026 ---%"
	fi
}

get_network() {
	# is_connected=$(ping -c 1 1.1.1.1 &> /dev/null || echo not)
	# is_connected=$(nmcli dev show wlp3s0 | grep "GENERAL.STATE" | tr -s "[:space:]" | rev | cut -d\  -f1 | rev)
	is_connected=$(iwctl station wlan0 show | head -6 | tail -n +6 | tr -s '[:space:]' | rev | cut -d\  -f1 | rev)	
	# if [[ ! $(echo "$is_connected" | wc -c) -gt 2 ]]; then
	if [[ "$is_connected" == "connected" ]]; then
		# ipv4=$(curl -s ifconfig.me)
		# [[ $(($(echo -n $ipv4 | wc -c) + 0)) -gt 5 ]] && ipv4="on" || ipv4="off"
		
		# get speed
		# tr=$(( $(ifstat wlp3s0 | tail -2 | head -1 | tr -s '[:space:]' | cut -d\  -f8) + 0))
		# (( $tr == "126" )) && tr=0
		# rc=$(($(ifstat wlp3s0 | tail -2 | head -1 | tr -s '[:space:]' | cut -d\  -f6) + 0))
		# up_ico="\\uf093"
		# down_ico="\\uf019"

		# Check VPN
		vpn="\\uf838"
		vpn_procs=$(($(ps aux | grep openvpn | wc -l) + 0))
		[[ $vpn_procs -gt 1 ]] && vpn="VPN "

		# echo "$vpn$down_ico $( printf %s $tr | numfmt --to=iec-i) $up_ico $( printf %s $rc | numfmt --to=iec-i)"  # Connected
		echo "$vpn"  # Connected
	else
		echo "\\uf839"  # Disconnected
	fi
}

status() {
	echo "$(get_network) $separator $(get_volume)"
}

date_info() {
	echo $(date +%d\ %B\ \'%y\ %R)
}

while true; do
	xsetroot -name " $(echo -e $(status) $separator $(date_info)) "
	# now=$(date +%s)
	# to=$((($(($now/60)) + 1) * 60))
	# sleep $(($to - $now + 1))
	sleep 5
done

